services:
  casestudy:
    build: .
    volumes:
      - ".:/case-study"
    command: simprov --state-file /case-study/study-state.pickle /case-study/patterns.yaml /case-study/rules.py
    ports:
        - "5000:5000"
  #web:
  #  image: andreasruscheinski/simprovweb
  #  ports:
  #      - "1234:1234"
  #  command: "npm run start"
